package org.group1.enums;

public enum POS {
    CC,  // COORDINATING CONJUNCTION
    CD,  // CARDINAL DIGIT
    DT,  // DETERMINER
    EX,  // EXISTENTIAL THERE
    FW,  // FOREING WORD
    IN,  // PREPOSITION
    JJ,  // ADJETIVE
    JJR, // ADJETIVE COMPARATIVE
    JJS, // ADJETIVE SUPERLATIVE
    LS,  // LIST ITEM MARKER
    MD,  // MODAL
    NN,  // NOUN SINGULAR
    NNS, // NOUN PLURAL
    NNP, // NOUN PROPER
    NNPS,// NOUN PROPER PLURAL
    PDT, // PREDETERMINER
    POS, // POSSESSIVE ENDING
    PRP, // PERSONAL PRONOUN
    PRP$,// POSSESSIVE PRONOUN
    RB,  // ADVERB
    RBR, // ADVERB COMPARATIVE
    RBS, // ADVERB SUPERLATIVE
    RP,  // PARTICLE
    SYM, // SYMBOL
    TO,  // INFINITE MARKER
    UH,  // INTERJECTION
    VB,  // VERB
    VBG, // VERB GERUND
    VBD, // VERB PAST TENSE
    VBN, // VERB PAST PARTICIPLE
    VBP, // VERB PRESENT
    VBZ, // VERB PRESENT 3RD PERSON
    WDT, // WH - DETERMINER
    WP,  // WH - PRONOUN
    WP$, // WH - POSSESSIVE
    WRB; // WH - ADVERB

}
